modLoader="javafml" #mandatory

loaderVersion="[37,)" #mandatory (36 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="gobber2" #mandatory
version="2.4.3" #mandatory
displayName="Gobber 2" #mandatory
description='''
Gobber into 1.17, It continues...!
'''


[[dependencies.gobber2]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.gobber2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
